kind: pipeline
type: docker
name: default

steps:
    - name: lint
      image: golangci/golangci-lint
      commands:
          - golangci-lint run

# ---
# kind: pipeline
# type: docker
# name: catalogdocker

# steps:
#     - name: docker (catalog-service)
#       image: plugins/docker
#       settings:
#           dockerfile: catalog/service/Dockerfile
#           username:
#               from_secret: gh_username
#           password:
#               from_secret: gh_token
#           registry: docker.pkg.github.com
#           repo: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/catalog
#       when:
#           branch:
#               - master
#               - develop
#           event:
#               exclude:
#                   - pull_request

# depends_on:
#     - lint

# ---
# kind: pipeline
# type: docker
# name: stockdocker

# steps:
#     - name: docker (stock-service)
#       image: plugins/docker
#       settings:
#           dockerfile: stock/service/Dockerfile
#           username:
#               from_secret: gh_username
#           password:
#               from_secret: gh_token
#           registry: docker.pkg.github.com
#           repo: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/stock
#       when:
#           branch:
#               - master
#               - develop
#           event:
#               exclude:
#                   - pull_request

# depends_on:
#     - lint

# ---
# kind: pipeline
# type: docker
# name: customerdocker

# steps:
#     - name: docker (customer-service)
#       image: plugins/docker
#       settings:
#           dockerfile: customer/service/Dockerfile
#           username:
#               from_secret: gh_username
#           password:
#               from_secret: gh_token
#           registry: docker.pkg.github.com
#           repo: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/customer
#       when:
#           branch:
#               - master
#               - develop
#           event:
#               exclude:
#                   - pull_request

# depends_on:
#     - lint  

# ---
# kind: pipeline
# type: docker
# name: orderdocker

# steps:
#     - name: docker (order-service)
#       image: plugins/docker
#       settings:
#           dockerfile: order/service/Dockerfile
#           username:
#               from_secret: gh_username
#           password:
#               from_secret: gh_token
#           registry: docker.pkg.github.com
#           repo: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/order
#       when:
#           branch:
#               - master
#               - develop
#           event:
#               exclude:
#                   - pull_request

# depends_on:
#     - lint  
    
# ---
# kind: pipeline
# type: docker
# name: paymentdocker

# steps:
#     - name: docker (payment-service)
#       image: plugins/docker
#       settings:
#           dockerfile: payment/service/Dockerfile
#           username:
#               from_secret: gh_username
#           password:
#               from_secret: gh_token
#           registry: docker.pkg.github.com
#           repo: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/payment
#       when:
#           branch:
#               - master
#               - develop
#           event:
#               exclude:
#                   - pull_request

# depends_on:
#     - lint     

# ---
# kind: pipeline
# type: docker
# name: shipmentdocker

# steps:
#     - name: docker (shipment-service)
#       image: plugins/docker
#       settings:
#           dockerfile: shipment/service/Dockerfile
#           username:
#               from_secret: gh_username
#           password:
#               from_secret: gh_token
#           registry: docker.pkg.github.com
#           repo: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/shipment
#       when:
#           branch:
#               - master
#               - develop
#           event:
#               exclude:
#                   - pull_request

# depends_on:
#     - lint  

# ---
# kind: pipeline
# type: docker
# name: client1docker

# steps:
#     - name: docker (client1)
#       image: plugins/docker
#       settings:
#           dockerfile: client1/service/Dockerfile
#           username:
#               from_secret: gh_username
#           password:
#               from_secret: gh_token
#           registry: docker.pkg.github.com
#           repo: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/client1
#       when:
#           branch:
#               - master
#               - develop
#           event:
#               exclude:
#                   - pull_request

# depends_on:
#     - lint  

# ---
# kind: pipeline
# type: docker
# name: client2docker

# steps:
#     - name: docker (client2)
#       image: plugins/docker
#       settings:
#           dockerfile: client2/service/Dockerfile
#           username:
#               from_secret: gh_username
#           password:
#               from_secret: gh_token
#           registry: docker.pkg.github.com
#           repo: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/client2
#       when:
#           branch:
#               - master
#               - develop
#           event:
#               exclude:
#                   - pull_request

# depends_on:
#     - lint  

# ---
# kind: pipeline
# type: docker
# name: client3docker

# steps:
#     - name: docker (client3)
#       image: plugins/docker
#       settings:
#           dockerfile: client3/service/Dockerfile
#           username:
#               from_secret: gh_username
#           password:
#               from_secret: gh_token
#           registry: docker.pkg.github.com
#           repo: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/client3
#       when:
#           branch:
#               - master
#               - develop
#           event:
#               exclude:
#                   - pull_request

# depends_on:
#     - lint   

# ---
# kind: pipeline
# type: docker
# name: client4docker

# steps:
#     - name: docker (client4)
#       image: plugins/docker
#       settings:
#           dockerfile: client4/service/Dockerfile
#           username:
#               from_secret: gh_username
#           password:
#               from_secret: gh_token
#           registry: docker.pkg.github.com
#           repo: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/client4
#       when:
#           branch:
#               - master
#               - develop
#           event:
#               exclude:
#                   - pull_request

# depends_on:
#     - lint 
    
# ---
# kind: pipeline
# type: docker
# name: start szenario

# steps:
#     - name: etcd
#       image: "bitnami/etcd:latest"
#       environment:
#           ALLOW_NONE_AUTHENTICATION: yes
#           ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
#       detach: true

#     - name: nats
#       image: nats
#       detach: true

#     - name: redis
#       image: "bitnami/redis:latest"
#       environment:
#           ALLOW_EMPTY_PASSWORD: yes
#       detach: true

#     - name: catalog
#       image: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/catalog:latest
#       environment:
#           ALLOW_NONE_AUTHENTICATION: yes
#       commands:
#           - sleep 5
#           - /app/catalog-service --registry_address=etcd:2379
#       detach: true

#     - name: stock
#       image: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/stock:latest
#       environment:
#           ALLOW_NONE_AUTHENTICATION: yes
#       commands:
#           - sleep 5
#           - /app/stock-service --registry_address=etcd:2379
#       detach: true      

#     - name: customer
#       image: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/customer:latest
#       environment:
#           ALLOW_NONE_AUTHENTICATION: yes
#       commands:
#           - sleep 5
#           - /app/customer-service --registry_address=etcd:2379
#       detach: true            

#     - name: order
#       image: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/order:latest
#       environment:
#           ALLOW_NONE_AUTHENTICATION: yes
#       commands:
#           - sleep 5
#           - /app/order-service --registry_address=etcd:2379  --broker_address=nats:4222
#       detach: true

#     - name: payment
#       image: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/payment:latest
#       environment:
#           ALLOW_NONE_AUTHENTICATION: yes
#       commands:
#           - sleep 5
#           - /app/payment-service --registry_address=etcd:2379  --broker_address=nats:4222 
#       detach: true

#     - name: shipment
#       image: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/shipment:latest
#       environment:
#           ALLOW_NONE_AUTHENTICATION: yes
#       commands:
#           - sleep 5
#           - /app/shipment-service --registry_address=etcd:2379  --broker_address=nats:4222 
#       detach: true

#     - name: client1
#       image: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/client1:latest
#       environment:
#           ALLOW_NONE_AUTHENTICATION: yes
#       commands:
#           - sleep 5
#           - /app/client1 --registry_address=etcd:2379

#    - name: client2
#      image: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/client2:latest
#      environment:
#          ALLOW_NONE_AUTHENTICATION: yes
#      commands:
#         - sleep 5
#          - /app/client2 --registry_address=etcd:2379

#    - name: client3
#     image: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/client3:latest
#      environment:
#          ALLOW_NONE_AUTHENTICATION: yes
#      commands:
#          - sleep 5
#          - /app/client3 --registry_address=etcd:2379

#    - name: client4
#      image: docker.pkg.github.com/ob-vss-20ss/blatt2-cyan/client4:latest
#      environment:
#          ALLOW_NONE_AUTHENTICATION: yes
#      commands:
#         - sleep 5
#          - /app/client4 --registry_address=etcd:2379

#depends_on:
##    - catalogdocker
#    - stockdocker
#    - customerdocker
#    - orderdocker
#    - paymentdocker
#    - shipmentdocker
#    - client1docker
#    - client2docker
#    - client3docker
#    - client4docker

# # als Secret dockerconfig
# # das AuthToken bekommen Sie als Ergebnis des Aufrufs
# # echo -u username:token | base64
# # {
# # 	"auths": {
# # 		"docker.pkg.github.com": {
# # 			"auth": "YW11cmRhY2E6c3VwZXJzZWNyZXRwYXNzd29yZA=="
# # 		}
# # 	}
# # }

# image_pull_secrets:
#     - dockerconfig
