// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	ItemID               uint32   `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price                uint32   `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Available            uint32   `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetItemID() uint32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetAvailable() uint32 {
	if m != nil {
		return m.Available
	}
	return 0
}

type ItemsInStockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsInStockRequest) Reset()         { *m = ItemsInStockRequest{} }
func (m *ItemsInStockRequest) String() string { return proto.CompactTextString(m) }
func (*ItemsInStockRequest) ProtoMessage()    {}
func (*ItemsInStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *ItemsInStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsInStockRequest.Unmarshal(m, b)
}
func (m *ItemsInStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsInStockRequest.Marshal(b, m, deterministic)
}
func (m *ItemsInStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsInStockRequest.Merge(m, src)
}
func (m *ItemsInStockRequest) XXX_Size() int {
	return xxx_messageInfo_ItemsInStockRequest.Size(m)
}
func (m *ItemsInStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsInStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsInStockRequest proto.InternalMessageInfo

type ItemsInStockResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsInStockResponse) Reset()         { *m = ItemsInStockResponse{} }
func (m *ItemsInStockResponse) String() string { return proto.CompactTextString(m) }
func (*ItemsInStockResponse) ProtoMessage()    {}
func (*ItemsInStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *ItemsInStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsInStockResponse.Unmarshal(m, b)
}
func (m *ItemsInStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsInStockResponse.Marshal(b, m, deterministic)
}
func (m *ItemsInStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsInStockResponse.Merge(m, src)
}
func (m *ItemsInStockResponse) XXX_Size() int {
	return xxx_messageInfo_ItemsInStockResponse.Size(m)
}
func (m *ItemsInStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsInStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsInStockResponse proto.InternalMessageInfo

func (m *ItemsInStockResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type StockOfItemRequest struct {
	ItemID               uint32   `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockOfItemRequest) Reset()         { *m = StockOfItemRequest{} }
func (m *StockOfItemRequest) String() string { return proto.CompactTextString(m) }
func (*StockOfItemRequest) ProtoMessage()    {}
func (*StockOfItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *StockOfItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockOfItemRequest.Unmarshal(m, b)
}
func (m *StockOfItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockOfItemRequest.Marshal(b, m, deterministic)
}
func (m *StockOfItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockOfItemRequest.Merge(m, src)
}
func (m *StockOfItemRequest) XXX_Size() int {
	return xxx_messageInfo_StockOfItemRequest.Size(m)
}
func (m *StockOfItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StockOfItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StockOfItemRequest proto.InternalMessageInfo

func (m *StockOfItemRequest) GetItemID() uint32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

type StockOfItemResponse struct {
	Stock                uint32   `protobuf:"varint,1,opt,name=stock,proto3" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockOfItemResponse) Reset()         { *m = StockOfItemResponse{} }
func (m *StockOfItemResponse) String() string { return proto.CompactTextString(m) }
func (*StockOfItemResponse) ProtoMessage()    {}
func (*StockOfItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{4}
}

func (m *StockOfItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockOfItemResponse.Unmarshal(m, b)
}
func (m *StockOfItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockOfItemResponse.Marshal(b, m, deterministic)
}
func (m *StockOfItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockOfItemResponse.Merge(m, src)
}
func (m *StockOfItemResponse) XXX_Size() int {
	return xxx_messageInfo_StockOfItemResponse.Size(m)
}
func (m *StockOfItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StockOfItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StockOfItemResponse proto.InternalMessageInfo

func (m *StockOfItemResponse) GetStock() uint32 {
	if m != nil {
		return m.Stock
	}
	return 0
}

type ReduceStockRequest struct {
	ItemID               uint32   `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Amount               uint32   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceStockRequest) Reset()         { *m = ReduceStockRequest{} }
func (m *ReduceStockRequest) String() string { return proto.CompactTextString(m) }
func (*ReduceStockRequest) ProtoMessage()    {}
func (*ReduceStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{5}
}

func (m *ReduceStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceStockRequest.Unmarshal(m, b)
}
func (m *ReduceStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceStockRequest.Marshal(b, m, deterministic)
}
func (m *ReduceStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceStockRequest.Merge(m, src)
}
func (m *ReduceStockRequest) XXX_Size() int {
	return xxx_messageInfo_ReduceStockRequest.Size(m)
}
func (m *ReduceStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceStockRequest proto.InternalMessageInfo

func (m *ReduceStockRequest) GetItemID() uint32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *ReduceStockRequest) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ReduceStockResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceStockResponse) Reset()         { *m = ReduceStockResponse{} }
func (m *ReduceStockResponse) String() string { return proto.CompactTextString(m) }
func (*ReduceStockResponse) ProtoMessage()    {}
func (*ReduceStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{6}
}

func (m *ReduceStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceStockResponse.Unmarshal(m, b)
}
func (m *ReduceStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceStockResponse.Marshal(b, m, deterministic)
}
func (m *ReduceStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceStockResponse.Merge(m, src)
}
func (m *ReduceStockResponse) XXX_Size() int {
	return xxx_messageInfo_ReduceStockResponse.Size(m)
}
func (m *ReduceStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceStockResponse proto.InternalMessageInfo

func (m *ReduceStockResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type IncreaseStockRequest struct {
	ItemID               uint32   `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Amount               uint32   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncreaseStockRequest) Reset()         { *m = IncreaseStockRequest{} }
func (m *IncreaseStockRequest) String() string { return proto.CompactTextString(m) }
func (*IncreaseStockRequest) ProtoMessage()    {}
func (*IncreaseStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{7}
}

func (m *IncreaseStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncreaseStockRequest.Unmarshal(m, b)
}
func (m *IncreaseStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncreaseStockRequest.Marshal(b, m, deterministic)
}
func (m *IncreaseStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseStockRequest.Merge(m, src)
}
func (m *IncreaseStockRequest) XXX_Size() int {
	return xxx_messageInfo_IncreaseStockRequest.Size(m)
}
func (m *IncreaseStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseStockRequest proto.InternalMessageInfo

func (m *IncreaseStockRequest) GetItemID() uint32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *IncreaseStockRequest) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type IncreaseStockResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncreaseStockResponse) Reset()         { *m = IncreaseStockResponse{} }
func (m *IncreaseStockResponse) String() string { return proto.CompactTextString(m) }
func (*IncreaseStockResponse) ProtoMessage()    {}
func (*IncreaseStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{8}
}

func (m *IncreaseStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncreaseStockResponse.Unmarshal(m, b)
}
func (m *IncreaseStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncreaseStockResponse.Marshal(b, m, deterministic)
}
func (m *IncreaseStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseStockResponse.Merge(m, src)
}
func (m *IncreaseStockResponse) XXX_Size() int {
	return xxx_messageInfo_IncreaseStockResponse.Size(m)
}
func (m *IncreaseStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseStockResponse proto.InternalMessageInfo

func (m *IncreaseStockResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type RegisterCustomerRequest struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCustomerRequest) Reset()         { *m = RegisterCustomerRequest{} }
func (m *RegisterCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerRequest) ProtoMessage()    {}
func (*RegisterCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{9}
}

func (m *RegisterCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerRequest.Unmarshal(m, b)
}
func (m *RegisterCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerRequest.Merge(m, src)
}
func (m *RegisterCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerRequest.Size(m)
}
func (m *RegisterCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerRequest proto.InternalMessageInfo

func (m *RegisterCustomerRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *RegisterCustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterCustomerRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RegisterCustomerResponse struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCustomerResponse) Reset()         { *m = RegisterCustomerResponse{} }
func (m *RegisterCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerResponse) ProtoMessage()    {}
func (*RegisterCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{10}
}

func (m *RegisterCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerResponse.Unmarshal(m, b)
}
func (m *RegisterCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerResponse.Marshal(b, m, deterministic)
}
func (m *RegisterCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerResponse.Merge(m, src)
}
func (m *RegisterCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerResponse.Size(m)
}
func (m *RegisterCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerResponse proto.InternalMessageInfo

func (m *RegisterCustomerResponse) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

type GetCustomerRequest struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerRequest) Reset()         { *m = GetCustomerRequest{} }
func (m *GetCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerRequest) ProtoMessage()    {}
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{11}
}

func (m *GetCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerRequest.Unmarshal(m, b)
}
func (m *GetCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerRequest.Marshal(b, m, deterministic)
}
func (m *GetCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerRequest.Merge(m, src)
}
func (m *GetCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomerRequest.Size(m)
}
func (m *GetCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerRequest proto.InternalMessageInfo

func (m *GetCustomerRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

type GetCustomerResponse struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerResponse) Reset()         { *m = GetCustomerResponse{} }
func (m *GetCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomerResponse) ProtoMessage()    {}
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{12}
}

func (m *GetCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerResponse.Unmarshal(m, b)
}
func (m *GetCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerResponse.Marshal(b, m, deterministic)
}
func (m *GetCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerResponse.Merge(m, src)
}
func (m *GetCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_GetCustomerResponse.Size(m)
}
func (m *GetCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerResponse proto.InternalMessageInfo

func (m *GetCustomerResponse) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *GetCustomerResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetCustomerResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteCustomerRequest struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomerRequest) Reset()         { *m = DeleteCustomerRequest{} }
func (m *DeleteCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomerRequest) ProtoMessage()    {}
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{13}
}

func (m *DeleteCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomerRequest.Unmarshal(m, b)
}
func (m *DeleteCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomerRequest.Merge(m, src)
}
func (m *DeleteCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomerRequest.Size(m)
}
func (m *DeleteCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomerRequest proto.InternalMessageInfo

func (m *DeleteCustomerRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

type DeleteCustomerResponse struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomerResponse) Reset()         { *m = DeleteCustomerResponse{} }
func (m *DeleteCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomerResponse) ProtoMessage()    {}
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{14}
}

func (m *DeleteCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomerResponse.Unmarshal(m, b)
}
func (m *DeleteCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomerResponse.Merge(m, src)
}
func (m *DeleteCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomerResponse.Size(m)
}
func (m *DeleteCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomerResponse proto.InternalMessageInfo

func (m *DeleteCustomerResponse) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

type PlaceOrderRequest struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceOrderRequest) Reset()         { *m = PlaceOrderRequest{} }
func (m *PlaceOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderRequest) ProtoMessage()    {}
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{15}
}

func (m *PlaceOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderRequest.Unmarshal(m, b)
}
func (m *PlaceOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderRequest.Marshal(b, m, deterministic)
}
func (m *PlaceOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderRequest.Merge(m, src)
}
func (m *PlaceOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderRequest.Size(m)
}
func (m *PlaceOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderRequest proto.InternalMessageInfo

func (m *PlaceOrderRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

type PlaceOrderResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceOrderResponse) Reset()         { *m = PlaceOrderResponse{} }
func (m *PlaceOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderResponse) ProtoMessage()    {}
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{16}
}

func (m *PlaceOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderResponse.Unmarshal(m, b)
}
func (m *PlaceOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderResponse.Marshal(b, m, deterministic)
}
func (m *PlaceOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderResponse.Merge(m, src)
}
func (m *PlaceOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderResponse.Size(m)
}
func (m *PlaceOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderResponse proto.InternalMessageInfo

func (m *PlaceOrderResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PlaceOrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReturnRequest struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	OrderID              uint32   `protobuf:"varint,2,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnRequest) Reset()         { *m = ReturnRequest{} }
func (m *ReturnRequest) String() string { return proto.CompactTextString(m) }
func (*ReturnRequest) ProtoMessage()    {}
func (*ReturnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{17}
}

func (m *ReturnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnRequest.Unmarshal(m, b)
}
func (m *ReturnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnRequest.Marshal(b, m, deterministic)
}
func (m *ReturnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnRequest.Merge(m, src)
}
func (m *ReturnRequest) XXX_Size() int {
	return xxx_messageInfo_ReturnRequest.Size(m)
}
func (m *ReturnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnRequest proto.InternalMessageInfo

func (m *ReturnRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *ReturnRequest) GetOrderID() uint32 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type ReturnResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnResponse) Reset()         { *m = ReturnResponse{} }
func (m *ReturnResponse) String() string { return proto.CompactTextString(m) }
func (*ReturnResponse) ProtoMessage()    {}
func (*ReturnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{18}
}

func (m *ReturnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnResponse.Unmarshal(m, b)
}
func (m *ReturnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnResponse.Marshal(b, m, deterministic)
}
func (m *ReturnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnResponse.Merge(m, src)
}
func (m *ReturnResponse) XXX_Size() int {
	return xxx_messageInfo_ReturnResponse.Size(m)
}
func (m *ReturnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnResponse proto.InternalMessageInfo

func (m *ReturnResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ReturnResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CancelRequest struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	OrderID              uint32   `protobuf:"varint,2,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelRequest) Reset()         { *m = CancelRequest{} }
func (m *CancelRequest) String() string { return proto.CompactTextString(m) }
func (*CancelRequest) ProtoMessage()    {}
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{19}
}

func (m *CancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRequest.Unmarshal(m, b)
}
func (m *CancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRequest.Marshal(b, m, deterministic)
}
func (m *CancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRequest.Merge(m, src)
}
func (m *CancelRequest) XXX_Size() int {
	return xxx_messageInfo_CancelRequest.Size(m)
}
func (m *CancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRequest proto.InternalMessageInfo

func (m *CancelRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *CancelRequest) GetOrderID() uint32 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type CancelResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelResponse) Reset()         { *m = CancelResponse{} }
func (m *CancelResponse) String() string { return proto.CompactTextString(m) }
func (*CancelResponse) ProtoMessage()    {}
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{20}
}

func (m *CancelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelResponse.Unmarshal(m, b)
}
func (m *CancelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelResponse.Marshal(b, m, deterministic)
}
func (m *CancelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelResponse.Merge(m, src)
}
func (m *CancelResponse) XXX_Size() int {
	return xxx_messageInfo_CancelResponse.Size(m)
}
func (m *CancelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelResponse proto.InternalMessageInfo

func (m *CancelResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CancelResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PaymentRequest struct {
	OrderID              uint32   `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentRequest) Reset()         { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()    {}
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{21}
}

func (m *PaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRequest.Unmarshal(m, b)
}
func (m *PaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRequest.Marshal(b, m, deterministic)
}
func (m *PaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequest.Merge(m, src)
}
func (m *PaymentRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentRequest.Size(m)
}
func (m *PaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequest proto.InternalMessageInfo

func (m *PaymentRequest) GetOrderID() uint32 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type PaymentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentResponse) Reset()         { *m = PaymentResponse{} }
func (m *PaymentResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentResponse) ProtoMessage()    {}
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{22}
}

func (m *PaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentResponse.Unmarshal(m, b)
}
func (m *PaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentResponse.Marshal(b, m, deterministic)
}
func (m *PaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentResponse.Merge(m, src)
}
func (m *PaymentResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentResponse.Size(m)
}
func (m *PaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentResponse proto.InternalMessageInfo

type PaymentEvent struct {
	OrderID              uint32   `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentEvent) Reset()         { *m = PaymentEvent{} }
func (m *PaymentEvent) String() string { return proto.CompactTextString(m) }
func (*PaymentEvent) ProtoMessage()    {}
func (*PaymentEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{23}
}

func (m *PaymentEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentEvent.Unmarshal(m, b)
}
func (m *PaymentEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentEvent.Marshal(b, m, deterministic)
}
func (m *PaymentEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentEvent.Merge(m, src)
}
func (m *PaymentEvent) XXX_Size() int {
	return xxx_messageInfo_PaymentEvent.Size(m)
}
func (m *PaymentEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentEvent proto.InternalMessageInfo

func (m *PaymentEvent) GetOrderID() uint32 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type ShipmentEvent struct {
	OrderID              uint32   `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipmentEvent) Reset()         { *m = ShipmentEvent{} }
func (m *ShipmentEvent) String() string { return proto.CompactTextString(m) }
func (*ShipmentEvent) ProtoMessage()    {}
func (*ShipmentEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{24}
}

func (m *ShipmentEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipmentEvent.Unmarshal(m, b)
}
func (m *ShipmentEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipmentEvent.Marshal(b, m, deterministic)
}
func (m *ShipmentEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipmentEvent.Merge(m, src)
}
func (m *ShipmentEvent) XXX_Size() int {
	return xxx_messageInfo_ShipmentEvent.Size(m)
}
func (m *ShipmentEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipmentEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ShipmentEvent proto.InternalMessageInfo

func (m *ShipmentEvent) GetOrderID() uint32 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func init() {
	proto.RegisterType((*Item)(nil), "api.Item")
	proto.RegisterType((*ItemsInStockRequest)(nil), "api.ItemsInStockRequest")
	proto.RegisterType((*ItemsInStockResponse)(nil), "api.ItemsInStockResponse")
	proto.RegisterType((*StockOfItemRequest)(nil), "api.StockOfItemRequest")
	proto.RegisterType((*StockOfItemResponse)(nil), "api.StockOfItemResponse")
	proto.RegisterType((*ReduceStockRequest)(nil), "api.ReduceStockRequest")
	proto.RegisterType((*ReduceStockResponse)(nil), "api.ReduceStockResponse")
	proto.RegisterType((*IncreaseStockRequest)(nil), "api.IncreaseStockRequest")
	proto.RegisterType((*IncreaseStockResponse)(nil), "api.IncreaseStockResponse")
	proto.RegisterType((*RegisterCustomerRequest)(nil), "api.RegisterCustomerRequest")
	proto.RegisterType((*RegisterCustomerResponse)(nil), "api.RegisterCustomerResponse")
	proto.RegisterType((*GetCustomerRequest)(nil), "api.GetCustomerRequest")
	proto.RegisterType((*GetCustomerResponse)(nil), "api.GetCustomerResponse")
	proto.RegisterType((*DeleteCustomerRequest)(nil), "api.DeleteCustomerRequest")
	proto.RegisterType((*DeleteCustomerResponse)(nil), "api.DeleteCustomerResponse")
	proto.RegisterType((*PlaceOrderRequest)(nil), "api.PlaceOrderRequest")
	proto.RegisterType((*PlaceOrderResponse)(nil), "api.PlaceOrderResponse")
	proto.RegisterType((*ReturnRequest)(nil), "api.ReturnRequest")
	proto.RegisterType((*ReturnResponse)(nil), "api.ReturnResponse")
	proto.RegisterType((*CancelRequest)(nil), "api.CancelRequest")
	proto.RegisterType((*CancelResponse)(nil), "api.CancelResponse")
	proto.RegisterType((*PaymentRequest)(nil), "api.PaymentRequest")
	proto.RegisterType((*PaymentResponse)(nil), "api.PaymentResponse")
	proto.RegisterType((*PaymentEvent)(nil), "api.PaymentEvent")
	proto.RegisterType((*ShipmentEvent)(nil), "api.ShipmentEvent")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 720 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0x4d, 0x08, 0x21, 0x70, 0xf8, 0x12, 0x3e, 0x26, 0x21, 0xb8, 0x2e, 0x6d, 0xd1, 0xac, 0xd2,
	0x1f, 0x81, 0x1a, 0x2a, 0x81, 0x5a, 0x55, 0x95, 0x20, 0x94, 0x44, 0x55, 0x05, 0x35, 0xbb, 0xee,
	0x06, 0xe7, 0x92, 0x5a, 0x4d, 0x6c, 0xd7, 0x9e, 0x20, 0xf5, 0xb1, 0xba, 0xee, 0x3b, 0xf5, 0x19,
	0x2a, 0xdb, 0x63, 0x63, 0xc7, 0xa6, 0x04, 0xc1, 0x2e, 0xf7, 0xef, 0x9c, 0x73, 0x27, 0x33, 0x47,
	0x46, 0x5d, 0xb8, 0xd6, 0xae, 0x70, 0xad, 0x1d, 0xd7, 0x73, 0xa4, 0xc3, 0x2a, 0xc2, 0xb5, 0xf8,
	0x25, 0x16, 0x07, 0x92, 0x26, 0xac, 0x8d, 0x25, 0x4b, 0xd2, 0x64, 0xd0, 0xd3, 0xca, 0xdb, 0xe5,
	0x4e, 0xdd, 0x50, 0x11, 0x63, 0x58, 0xb4, 0xc5, 0x84, 0xb4, 0x85, 0xed, 0x72, 0x67, 0xc5, 0x08,
	0x7f, 0xb3, 0x16, 0xaa, 0xae, 0x67, 0x99, 0xa4, 0x55, 0xc2, 0xd6, 0x28, 0x60, 0x5b, 0x58, 0x11,
	0x57, 0xc2, 0x1a, 0x8b, 0x8b, 0x31, 0x69, 0x8b, 0x61, 0xe5, 0x3a, 0xc1, 0x37, 0xd0, 0x0c, 0x78,
	0xfc, 0x81, 0x7d, 0x2e, 0x1d, 0xf3, 0xbb, 0x41, 0x3f, 0xa6, 0xe4, 0x4b, 0xbe, 0x8f, 0x56, 0x36,
	0xed, 0xbb, 0x8e, 0xed, 0x13, 0x7b, 0x86, 0x6a, 0x20, 0xc0, 0xd7, 0xca, 0xdb, 0x95, 0xce, 0x6a,
	0x77, 0x65, 0x27, 0x90, 0x1d, 0x74, 0x1a, 0x51, 0x9e, 0xbf, 0x02, 0x0b, 0x27, 0x4e, 0x2f, 0xc3,
	0x6c, 0x04, 0x77, 0xd3, 0x16, 0xfc, 0x25, 0x9a, 0x99, 0x6e, 0xc5, 0xd2, 0x42, 0xd5, 0x0f, 0xd2,
	0xaa, 0x3b, 0x0a, 0x78, 0x0f, 0xcc, 0xa0, 0xe1, 0xd4, 0xa4, 0xb4, 0xd2, 0x1b, 0x0f, 0xa8, 0x8d,
	0x25, 0x31, 0x71, 0xa6, 0xb6, 0x0c, 0x8f, 0xa8, 0x6e, 0xa8, 0x88, 0xef, 0xa2, 0x99, 0x41, 0x51,
	0x94, 0x1a, 0x6a, 0xfe, 0xd4, 0x34, 0xc9, 0xf7, 0x43, 0x9c, 0x65, 0x23, 0x0e, 0xf9, 0x47, 0xb4,
	0x06, 0xb6, 0xe9, 0x91, 0xf0, 0xef, 0x47, 0xfc, 0x1a, 0x1b, 0x33, 0x38, 0xb7, 0x52, 0x8f, 0xb0,
	0x69, 0xd0, 0xc8, 0xf2, 0x25, 0x79, 0x47, 0x53, 0x5f, 0x3a, 0x13, 0xf2, 0x62, 0xf6, 0xa7, 0x80,
	0xa9, 0x52, 0x89, 0x82, 0x54, 0xa6, 0xf0, 0x7e, 0x68, 0xa8, 0x89, 0xe1, 0xd0, 0x0b, 0x88, 0x2a,
	0x61, 0x3a, 0x0e, 0xf9, 0x5b, 0x68, 0x79, 0x22, 0x25, 0xef, 0x16, 0x26, 0xfe, 0x06, 0xec, 0x84,
	0xe4, 0x1d, 0xf5, 0x71, 0x13, 0xcd, 0xcc, 0xd4, 0x7c, 0x64, 0x77, 0x5c, 0x6b, 0x1f, 0x1b, 0x3d,
	0x1a, 0x93, 0xa4, 0xbb, 0xaa, 0x3b, 0x40, 0x7b, 0x76, 0x70, 0xce, 0xd3, 0xd8, 0xc3, 0xfa, 0xd9,
	0x58, 0x98, 0x74, 0xea, 0x0d, 0xe7, 0xa7, 0xeb, 0x83, 0xa5, 0x87, 0x6e, 0xbb, 0x17, 0x41, 0x65,
	0x42, 0xbe, 0x2f, 0x46, 0xf1, 0x41, 0xc4, 0x21, 0x1f, 0xa0, 0x6e, 0x90, 0x9c, 0x7a, 0xf6, 0xbc,
	0xf7, 0x44, 0x43, 0xcd, 0x09, 0x58, 0x07, 0x3d, 0x75, 0x5d, 0xe3, 0x90, 0xf7, 0xd0, 0x88, 0xa1,
	0xee, 0x27, 0xe8, 0x48, 0xd8, 0x26, 0x8d, 0x1f, 0x44, 0x50, 0x0c, 0x75, 0x0f, 0x41, 0x2f, 0xd0,
	0x38, 0x13, 0x3f, 0x27, 0x64, 0xcb, 0x58, 0x51, 0x8a, 0xb1, 0x9c, 0x65, 0x5c, 0xc7, 0x5a, 0xd2,
	0x1b, 0x51, 0xf2, 0x0e, 0xfe, 0x53, 0xa9, 0xe3, 0x2b, 0xb2, 0xff, 0x35, 0xfc, 0x1c, 0xf5, 0xf3,
	0x6f, 0x96, 0x3b, 0x47, 0x6b, 0xf7, 0x1c, 0xb5, 0x23, 0x21, 0xc5, 0xd8, 0x19, 0xb1, 0x3e, 0xd6,
	0x4e, 0x48, 0xa6, 0xbd, 0x97, 0x69, 0x89, 0xc9, 0xce, 0xb8, 0xb4, 0xfe, 0xa8, 0xa0, 0xa2, 0x74,
	0x96, 0xba, 0xbf, 0x16, 0x50, 0x8d, 0x00, 0x1e, 0x0c, 0x93, 0x1d, 0xa3, 0x71, 0x42, 0x32, 0x65,
	0xd9, 0x6c, 0x33, 0x6c, 0xcf, 0x5b, 0xbe, 0xae, 0xe5, 0x0b, 0x09, 0x4c, 0x1f, 0xeb, 0x29, 0x0f,
	0xce, 0x20, 0xe5, 0x1d, 0x5e, 0x21, 0x15, 0x98, 0x36, 0x2f, 0xb1, 0xcf, 0x60, 0x91, 0xa9, 0x66,
	0xa0, 0xd4, 0x0e, 0x05, 0xae, 0xad, 0xeb, 0x45, 0xa5, 0xe4, 0xcc, 0xfe, 0x94, 0xb1, 0x1c, 0x3f,
	0x79, 0xf6, 0x05, 0xff, 0xcf, 0x9a, 0x22, 0xdb, 0x52, 0x5a, 0x0a, 0x4d, 0x59, 0x7f, 0x72, 0x43,
	0x35, 0x91, 0x7b, 0x88, 0xd5, 0x94, 0xeb, 0xa9, 0x95, 0xf3, 0xee, 0xa9, 0x56, 0x2e, 0x30, 0x48,
	0x5e, 0x62, 0x9f, 0xd0, 0xc8, 0x7a, 0x13, 0x8b, 0x76, 0x2a, 0x74, 0x3a, 0xfd, 0x71, 0x61, 0x2d,
	0x59, 0xf8, 0x77, 0x19, 0xd5, 0xd0, 0x75, 0xd8, 0x07, 0xe0, 0xda, 0x83, 0x58, 0x3b, 0x1c, 0xcb,
	0x39, 0x99, 0xbe, 0x99, 0xcb, 0x27, 0xba, 0xf6, 0x81, 0xc8, 0x2f, 0xc2, 0xbf, 0x80, 0xa9, 0xa3,
	0x48, 0x79, 0x91, 0xde, 0xcc, 0xe4, 0x92, 0xc1, 0x03, 0xac, 0x46, 0xef, 0x3a, 0xa2, 0x8e, 0x26,
	0x33, 0xa6, 0xa1, 0x26, 0xb3, 0xaf, 0x9f, 0x97, 0xba, 0x7d, 0xd4, 0xd4, 0x63, 0x64, 0xef, 0x03,
	0xb7, 0x32, 0xc9, 0xba, 0xa2, 0x38, 0x13, 0xcd, 0x64, 0xdf, 0xba, 0xde, 0xca, 0x26, 0x13, 0x24,
	0x60, 0x39, 0x7e, 0xac, 0x87, 0xb5, 0xaf, 0xd5, 0x9d, 0x77, 0xc2, 0xb5, 0x2e, 0x96, 0xc2, 0xef,
	0xb1, 0xbd, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xf7, 0x6c, 0x39, 0xa0, 0x09, 0x00, 0x00,
}
