// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	ArticleID            uint32   `protobuf:"varint,1,opt,name=ArticleID,proto3" json:"ArticleID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price                uint32   `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`
	Available            uint32   `protobuf:"varint,4,opt,name=Available,proto3" json:"Available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetArticleID() uint32 {
	if m != nil {
		return m.ArticleID
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetAvailable() uint32 {
	if m != nil {
		return m.Available
	}
	return 0
}

type ItemsInStockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsInStockRequest) Reset()         { *m = ItemsInStockRequest{} }
func (m *ItemsInStockRequest) String() string { return proto.CompactTextString(m) }
func (*ItemsInStockRequest) ProtoMessage()    {}
func (*ItemsInStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *ItemsInStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsInStockRequest.Unmarshal(m, b)
}
func (m *ItemsInStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsInStockRequest.Marshal(b, m, deterministic)
}
func (m *ItemsInStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsInStockRequest.Merge(m, src)
}
func (m *ItemsInStockRequest) XXX_Size() int {
	return xxx_messageInfo_ItemsInStockRequest.Size(m)
}
func (m *ItemsInStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsInStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsInStockRequest proto.InternalMessageInfo

type ItemsInStockResponse struct {
	Items                []*Item  `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemsInStockResponse) Reset()         { *m = ItemsInStockResponse{} }
func (m *ItemsInStockResponse) String() string { return proto.CompactTextString(m) }
func (*ItemsInStockResponse) ProtoMessage()    {}
func (*ItemsInStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *ItemsInStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemsInStockResponse.Unmarshal(m, b)
}
func (m *ItemsInStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemsInStockResponse.Marshal(b, m, deterministic)
}
func (m *ItemsInStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemsInStockResponse.Merge(m, src)
}
func (m *ItemsInStockResponse) XXX_Size() int {
	return xxx_messageInfo_ItemsInStockResponse.Size(m)
}
func (m *ItemsInStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemsInStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemsInStockResponse proto.InternalMessageInfo

func (m *ItemsInStockResponse) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type ItemRequest struct {
	ArticleID            uint32   `protobuf:"varint,1,opt,name=ArticleID,proto3" json:"ArticleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemRequest) Reset()         { *m = ItemRequest{} }
func (m *ItemRequest) String() string { return proto.CompactTextString(m) }
func (*ItemRequest) ProtoMessage()    {}
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *ItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRequest.Unmarshal(m, b)
}
func (m *ItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRequest.Marshal(b, m, deterministic)
}
func (m *ItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRequest.Merge(m, src)
}
func (m *ItemRequest) XXX_Size() int {
	return xxx_messageInfo_ItemRequest.Size(m)
}
func (m *ItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRequest proto.InternalMessageInfo

func (m *ItemRequest) GetArticleID() uint32 {
	if m != nil {
		return m.ArticleID
	}
	return 0
}

type ItemResponse struct {
	ArticleID            uint32   `protobuf:"varint,1,opt,name=ArticleID,proto3" json:"ArticleID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price                uint32   `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemResponse) Reset()         { *m = ItemResponse{} }
func (m *ItemResponse) String() string { return proto.CompactTextString(m) }
func (*ItemResponse) ProtoMessage()    {}
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{4}
}

func (m *ItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemResponse.Unmarshal(m, b)
}
func (m *ItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemResponse.Marshal(b, m, deterministic)
}
func (m *ItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemResponse.Merge(m, src)
}
func (m *ItemResponse) XXX_Size() int {
	return xxx_messageInfo_ItemResponse.Size(m)
}
func (m *ItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemResponse proto.InternalMessageInfo

func (m *ItemResponse) GetArticleID() uint32 {
	if m != nil {
		return m.ArticleID
	}
	return 0
}

func (m *ItemResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ItemResponse) GetPrice() uint32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type StockOfItemRequest struct {
	ArticleID            uint32   `protobuf:"varint,1,opt,name=ArticleID,proto3" json:"ArticleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockOfItemRequest) Reset()         { *m = StockOfItemRequest{} }
func (m *StockOfItemRequest) String() string { return proto.CompactTextString(m) }
func (*StockOfItemRequest) ProtoMessage()    {}
func (*StockOfItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{5}
}

func (m *StockOfItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockOfItemRequest.Unmarshal(m, b)
}
func (m *StockOfItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockOfItemRequest.Marshal(b, m, deterministic)
}
func (m *StockOfItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockOfItemRequest.Merge(m, src)
}
func (m *StockOfItemRequest) XXX_Size() int {
	return xxx_messageInfo_StockOfItemRequest.Size(m)
}
func (m *StockOfItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StockOfItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StockOfItemRequest proto.InternalMessageInfo

func (m *StockOfItemRequest) GetArticleID() uint32 {
	if m != nil {
		return m.ArticleID
	}
	return 0
}

type StockOfItemResponse struct {
	Amount               uint32   `protobuf:"varint,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockOfItemResponse) Reset()         { *m = StockOfItemResponse{} }
func (m *StockOfItemResponse) String() string { return proto.CompactTextString(m) }
func (*StockOfItemResponse) ProtoMessage()    {}
func (*StockOfItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{6}
}

func (m *StockOfItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockOfItemResponse.Unmarshal(m, b)
}
func (m *StockOfItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockOfItemResponse.Marshal(b, m, deterministic)
}
func (m *StockOfItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockOfItemResponse.Merge(m, src)
}
func (m *StockOfItemResponse) XXX_Size() int {
	return xxx_messageInfo_StockOfItemResponse.Size(m)
}
func (m *StockOfItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StockOfItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StockOfItemResponse proto.InternalMessageInfo

func (m *StockOfItemResponse) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ReduceStockRequest struct {
	ArticleID            uint32   `protobuf:"varint,1,opt,name=ArticleID,proto3" json:"ArticleID,omitempty"`
	Amount               uint32   `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceStockRequest) Reset()         { *m = ReduceStockRequest{} }
func (m *ReduceStockRequest) String() string { return proto.CompactTextString(m) }
func (*ReduceStockRequest) ProtoMessage()    {}
func (*ReduceStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{7}
}

func (m *ReduceStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceStockRequest.Unmarshal(m, b)
}
func (m *ReduceStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceStockRequest.Marshal(b, m, deterministic)
}
func (m *ReduceStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceStockRequest.Merge(m, src)
}
func (m *ReduceStockRequest) XXX_Size() int {
	return xxx_messageInfo_ReduceStockRequest.Size(m)
}
func (m *ReduceStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceStockRequest proto.InternalMessageInfo

func (m *ReduceStockRequest) GetArticleID() uint32 {
	if m != nil {
		return m.ArticleID
	}
	return 0
}

func (m *ReduceStockRequest) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ReduceStockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduceStockResponse) Reset()         { *m = ReduceStockResponse{} }
func (m *ReduceStockResponse) String() string { return proto.CompactTextString(m) }
func (*ReduceStockResponse) ProtoMessage()    {}
func (*ReduceStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{8}
}

func (m *ReduceStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduceStockResponse.Unmarshal(m, b)
}
func (m *ReduceStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduceStockResponse.Marshal(b, m, deterministic)
}
func (m *ReduceStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduceStockResponse.Merge(m, src)
}
func (m *ReduceStockResponse) XXX_Size() int {
	return xxx_messageInfo_ReduceStockResponse.Size(m)
}
func (m *ReduceStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduceStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReduceStockResponse proto.InternalMessageInfo

type IncreaseStockRequest struct {
	ArticleID            uint32   `protobuf:"varint,1,opt,name=ArticleID,proto3" json:"ArticleID,omitempty"`
	Amount               uint32   `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncreaseStockRequest) Reset()         { *m = IncreaseStockRequest{} }
func (m *IncreaseStockRequest) String() string { return proto.CompactTextString(m) }
func (*IncreaseStockRequest) ProtoMessage()    {}
func (*IncreaseStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{9}
}

func (m *IncreaseStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncreaseStockRequest.Unmarshal(m, b)
}
func (m *IncreaseStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncreaseStockRequest.Marshal(b, m, deterministic)
}
func (m *IncreaseStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseStockRequest.Merge(m, src)
}
func (m *IncreaseStockRequest) XXX_Size() int {
	return xxx_messageInfo_IncreaseStockRequest.Size(m)
}
func (m *IncreaseStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseStockRequest proto.InternalMessageInfo

func (m *IncreaseStockRequest) GetArticleID() uint32 {
	if m != nil {
		return m.ArticleID
	}
	return 0
}

func (m *IncreaseStockRequest) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type IncreaseStockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncreaseStockResponse) Reset()         { *m = IncreaseStockResponse{} }
func (m *IncreaseStockResponse) String() string { return proto.CompactTextString(m) }
func (*IncreaseStockResponse) ProtoMessage()    {}
func (*IncreaseStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{10}
}

func (m *IncreaseStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncreaseStockResponse.Unmarshal(m, b)
}
func (m *IncreaseStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncreaseStockResponse.Marshal(b, m, deterministic)
}
func (m *IncreaseStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncreaseStockResponse.Merge(m, src)
}
func (m *IncreaseStockResponse) XXX_Size() int {
	return xxx_messageInfo_IncreaseStockResponse.Size(m)
}
func (m *IncreaseStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IncreaseStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IncreaseStockResponse proto.InternalMessageInfo

type RegisterCustomerRequest struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCustomerRequest) Reset()         { *m = RegisterCustomerRequest{} }
func (m *RegisterCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerRequest) ProtoMessage()    {}
func (*RegisterCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{11}
}

func (m *RegisterCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerRequest.Unmarshal(m, b)
}
func (m *RegisterCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerRequest.Merge(m, src)
}
func (m *RegisterCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerRequest.Size(m)
}
func (m *RegisterCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerRequest proto.InternalMessageInfo

func (m *RegisterCustomerRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *RegisterCustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterCustomerRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RegisterCustomerResponse struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterCustomerResponse) Reset()         { *m = RegisterCustomerResponse{} }
func (m *RegisterCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterCustomerResponse) ProtoMessage()    {}
func (*RegisterCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{12}
}

func (m *RegisterCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterCustomerResponse.Unmarshal(m, b)
}
func (m *RegisterCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterCustomerResponse.Marshal(b, m, deterministic)
}
func (m *RegisterCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCustomerResponse.Merge(m, src)
}
func (m *RegisterCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterCustomerResponse.Size(m)
}
func (m *RegisterCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCustomerResponse proto.InternalMessageInfo

func (m *RegisterCustomerResponse) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

type GetCustomerRequest struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerRequest) Reset()         { *m = GetCustomerRequest{} }
func (m *GetCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerRequest) ProtoMessage()    {}
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{13}
}

func (m *GetCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerRequest.Unmarshal(m, b)
}
func (m *GetCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerRequest.Marshal(b, m, deterministic)
}
func (m *GetCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerRequest.Merge(m, src)
}
func (m *GetCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomerRequest.Size(m)
}
func (m *GetCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerRequest proto.InternalMessageInfo

func (m *GetCustomerRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

type GetCustomerResponse struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerResponse) Reset()         { *m = GetCustomerResponse{} }
func (m *GetCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomerResponse) ProtoMessage()    {}
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{14}
}

func (m *GetCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerResponse.Unmarshal(m, b)
}
func (m *GetCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerResponse.Marshal(b, m, deterministic)
}
func (m *GetCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerResponse.Merge(m, src)
}
func (m *GetCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_GetCustomerResponse.Size(m)
}
func (m *GetCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerResponse proto.InternalMessageInfo

func (m *GetCustomerResponse) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *GetCustomerResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetCustomerResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DeleteCustomerRequest struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomerRequest) Reset()         { *m = DeleteCustomerRequest{} }
func (m *DeleteCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomerRequest) ProtoMessage()    {}
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{15}
}

func (m *DeleteCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomerRequest.Unmarshal(m, b)
}
func (m *DeleteCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomerRequest.Marshal(b, m, deterministic)
}
func (m *DeleteCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomerRequest.Merge(m, src)
}
func (m *DeleteCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomerRequest.Size(m)
}
func (m *DeleteCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomerRequest proto.InternalMessageInfo

func (m *DeleteCustomerRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

type DeleteCustomerResponse struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteCustomerResponse) Reset()         { *m = DeleteCustomerResponse{} }
func (m *DeleteCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteCustomerResponse) ProtoMessage()    {}
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{16}
}

func (m *DeleteCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteCustomerResponse.Unmarshal(m, b)
}
func (m *DeleteCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteCustomerResponse.Marshal(b, m, deterministic)
}
func (m *DeleteCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteCustomerResponse.Merge(m, src)
}
func (m *DeleteCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteCustomerResponse.Size(m)
}
func (m *DeleteCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteCustomerResponse proto.InternalMessageInfo

func (m *DeleteCustomerResponse) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

type ArticleWithAmount struct {
	ArticleID            uint32   `protobuf:"varint,1,opt,name=ArticleID,proto3" json:"ArticleID,omitempty"`
	Amount               uint32   `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleWithAmount) Reset()         { *m = ArticleWithAmount{} }
func (m *ArticleWithAmount) String() string { return proto.CompactTextString(m) }
func (*ArticleWithAmount) ProtoMessage()    {}
func (*ArticleWithAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{17}
}

func (m *ArticleWithAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleWithAmount.Unmarshal(m, b)
}
func (m *ArticleWithAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleWithAmount.Marshal(b, m, deterministic)
}
func (m *ArticleWithAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleWithAmount.Merge(m, src)
}
func (m *ArticleWithAmount) XXX_Size() int {
	return xxx_messageInfo_ArticleWithAmount.Size(m)
}
func (m *ArticleWithAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleWithAmount.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleWithAmount proto.InternalMessageInfo

func (m *ArticleWithAmount) GetArticleID() uint32 {
	if m != nil {
		return m.ArticleID
	}
	return 0
}

func (m *ArticleWithAmount) GetAmount() uint32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type PlaceOrderRequest struct {
	CustomerID           uint32               `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	ArticleList          []*ArticleWithAmount `protobuf:"bytes,2,rep,name=articleList,proto3" json:"articleList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PlaceOrderRequest) Reset()         { *m = PlaceOrderRequest{} }
func (m *PlaceOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderRequest) ProtoMessage()    {}
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{18}
}

func (m *PlaceOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderRequest.Unmarshal(m, b)
}
func (m *PlaceOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderRequest.Marshal(b, m, deterministic)
}
func (m *PlaceOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderRequest.Merge(m, src)
}
func (m *PlaceOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderRequest.Size(m)
}
func (m *PlaceOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderRequest proto.InternalMessageInfo

func (m *PlaceOrderRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *PlaceOrderRequest) GetArticleList() []*ArticleWithAmount {
	if m != nil {
		return m.ArticleList
	}
	return nil
}

type PlaceOrderResponse struct {
	OrderID              uint32   `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceOrderResponse) Reset()         { *m = PlaceOrderResponse{} }
func (m *PlaceOrderResponse) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderResponse) ProtoMessage()    {}
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{19}
}

func (m *PlaceOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderResponse.Unmarshal(m, b)
}
func (m *PlaceOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderResponse.Marshal(b, m, deterministic)
}
func (m *PlaceOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderResponse.Merge(m, src)
}
func (m *PlaceOrderResponse) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderResponse.Size(m)
}
func (m *PlaceOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderResponse proto.InternalMessageInfo

func (m *PlaceOrderResponse) GetOrderID() uint32 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func (m *PlaceOrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ReturnRequest struct {
	CustomerID           uint32               `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	OrderID              uint32               `protobuf:"varint,2,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	Replacement          bool                 `protobuf:"varint,3,opt,name=Replacement,proto3" json:"Replacement,omitempty"`
	ArticleList          []*ArticleWithAmount `protobuf:"bytes,4,rep,name=ArticleList,proto3" json:"ArticleList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReturnRequest) Reset()         { *m = ReturnRequest{} }
func (m *ReturnRequest) String() string { return proto.CompactTextString(m) }
func (*ReturnRequest) ProtoMessage()    {}
func (*ReturnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{20}
}

func (m *ReturnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnRequest.Unmarshal(m, b)
}
func (m *ReturnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnRequest.Marshal(b, m, deterministic)
}
func (m *ReturnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnRequest.Merge(m, src)
}
func (m *ReturnRequest) XXX_Size() int {
	return xxx_messageInfo_ReturnRequest.Size(m)
}
func (m *ReturnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnRequest proto.InternalMessageInfo

func (m *ReturnRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *ReturnRequest) GetOrderID() uint32 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func (m *ReturnRequest) GetReplacement() bool {
	if m != nil {
		return m.Replacement
	}
	return false
}

func (m *ReturnRequest) GetArticleList() []*ArticleWithAmount {
	if m != nil {
		return m.ArticleList
	}
	return nil
}

type ReturnResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnResponse) Reset()         { *m = ReturnResponse{} }
func (m *ReturnResponse) String() string { return proto.CompactTextString(m) }
func (*ReturnResponse) ProtoMessage()    {}
func (*ReturnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{21}
}

func (m *ReturnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnResponse.Unmarshal(m, b)
}
func (m *ReturnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnResponse.Marshal(b, m, deterministic)
}
func (m *ReturnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnResponse.Merge(m, src)
}
func (m *ReturnResponse) XXX_Size() int {
	return xxx_messageInfo_ReturnResponse.Size(m)
}
func (m *ReturnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnResponse proto.InternalMessageInfo

func (m *ReturnResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CancelRequest struct {
	CustomerID           uint32   `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	OrderID              uint32   `protobuf:"varint,2,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelRequest) Reset()         { *m = CancelRequest{} }
func (m *CancelRequest) String() string { return proto.CompactTextString(m) }
func (*CancelRequest) ProtoMessage()    {}
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{22}
}

func (m *CancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelRequest.Unmarshal(m, b)
}
func (m *CancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelRequest.Marshal(b, m, deterministic)
}
func (m *CancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelRequest.Merge(m, src)
}
func (m *CancelRequest) XXX_Size() int {
	return xxx_messageInfo_CancelRequest.Size(m)
}
func (m *CancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelRequest proto.InternalMessageInfo

func (m *CancelRequest) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *CancelRequest) GetOrderID() uint32 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type CancelResponse struct {
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelResponse) Reset()         { *m = CancelResponse{} }
func (m *CancelResponse) String() string { return proto.CompactTextString(m) }
func (*CancelResponse) ProtoMessage()    {}
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{23}
}

func (m *CancelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelResponse.Unmarshal(m, b)
}
func (m *CancelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelResponse.Marshal(b, m, deterministic)
}
func (m *CancelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelResponse.Merge(m, src)
}
func (m *CancelResponse) XXX_Size() int {
	return xxx_messageInfo_CancelResponse.Size(m)
}
func (m *CancelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelResponse proto.InternalMessageInfo

func (m *CancelResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetOrderRequest struct {
	OrderID              uint32   `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderRequest) Reset()         { *m = GetOrderRequest{} }
func (m *GetOrderRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrderRequest) ProtoMessage()    {}
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{24}
}

func (m *GetOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderRequest.Unmarshal(m, b)
}
func (m *GetOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderRequest.Marshal(b, m, deterministic)
}
func (m *GetOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderRequest.Merge(m, src)
}
func (m *GetOrderRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrderRequest.Size(m)
}
func (m *GetOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderRequest proto.InternalMessageInfo

func (m *GetOrderRequest) GetOrderID() uint32 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type GetOrderResponse struct {
	CustomerID           uint32               `protobuf:"varint,1,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	ArticleList          []*ArticleWithAmount `protobuf:"bytes,2,rep,name=ArticleList,proto3" json:"ArticleList,omitempty"`
	Paid                 bool                 `protobuf:"varint,3,opt,name=Paid,proto3" json:"Paid,omitempty"`
	Shipped              bool                 `protobuf:"varint,4,opt,name=Shipped,proto3" json:"Shipped,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetOrderResponse) Reset()         { *m = GetOrderResponse{} }
func (m *GetOrderResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrderResponse) ProtoMessage()    {}
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{25}
}

func (m *GetOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResponse.Unmarshal(m, b)
}
func (m *GetOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResponse.Marshal(b, m, deterministic)
}
func (m *GetOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResponse.Merge(m, src)
}
func (m *GetOrderResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrderResponse.Size(m)
}
func (m *GetOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResponse proto.InternalMessageInfo

func (m *GetOrderResponse) GetCustomerID() uint32 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *GetOrderResponse) GetArticleList() []*ArticleWithAmount {
	if m != nil {
		return m.ArticleList
	}
	return nil
}

func (m *GetOrderResponse) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func (m *GetOrderResponse) GetShipped() bool {
	if m != nil {
		return m.Shipped
	}
	return false
}

type PaymentRequest struct {
	OrderID              uint32   `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentRequest) Reset()         { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()    {}
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{26}
}

func (m *PaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentRequest.Unmarshal(m, b)
}
func (m *PaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentRequest.Marshal(b, m, deterministic)
}
func (m *PaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentRequest.Merge(m, src)
}
func (m *PaymentRequest) XXX_Size() int {
	return xxx_messageInfo_PaymentRequest.Size(m)
}
func (m *PaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentRequest proto.InternalMessageInfo

func (m *PaymentRequest) GetOrderID() uint32 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type PaymentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentResponse) Reset()         { *m = PaymentResponse{} }
func (m *PaymentResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentResponse) ProtoMessage()    {}
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{27}
}

func (m *PaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentResponse.Unmarshal(m, b)
}
func (m *PaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentResponse.Marshal(b, m, deterministic)
}
func (m *PaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentResponse.Merge(m, src)
}
func (m *PaymentResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentResponse.Size(m)
}
func (m *PaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentResponse proto.InternalMessageInfo

type Event struct {
	// unique id
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// unix timestamp
	Timestamp int64 `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	// message
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{28}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "api.Item")
	proto.RegisterType((*ItemsInStockRequest)(nil), "api.ItemsInStockRequest")
	proto.RegisterType((*ItemsInStockResponse)(nil), "api.ItemsInStockResponse")
	proto.RegisterType((*ItemRequest)(nil), "api.ItemRequest")
	proto.RegisterType((*ItemResponse)(nil), "api.ItemResponse")
	proto.RegisterType((*StockOfItemRequest)(nil), "api.StockOfItemRequest")
	proto.RegisterType((*StockOfItemResponse)(nil), "api.StockOfItemResponse")
	proto.RegisterType((*ReduceStockRequest)(nil), "api.ReduceStockRequest")
	proto.RegisterType((*ReduceStockResponse)(nil), "api.ReduceStockResponse")
	proto.RegisterType((*IncreaseStockRequest)(nil), "api.IncreaseStockRequest")
	proto.RegisterType((*IncreaseStockResponse)(nil), "api.IncreaseStockResponse")
	proto.RegisterType((*RegisterCustomerRequest)(nil), "api.RegisterCustomerRequest")
	proto.RegisterType((*RegisterCustomerResponse)(nil), "api.RegisterCustomerResponse")
	proto.RegisterType((*GetCustomerRequest)(nil), "api.GetCustomerRequest")
	proto.RegisterType((*GetCustomerResponse)(nil), "api.GetCustomerResponse")
	proto.RegisterType((*DeleteCustomerRequest)(nil), "api.DeleteCustomerRequest")
	proto.RegisterType((*DeleteCustomerResponse)(nil), "api.DeleteCustomerResponse")
	proto.RegisterType((*ArticleWithAmount)(nil), "api.ArticleWithAmount")
	proto.RegisterType((*PlaceOrderRequest)(nil), "api.PlaceOrderRequest")
	proto.RegisterType((*PlaceOrderResponse)(nil), "api.PlaceOrderResponse")
	proto.RegisterType((*ReturnRequest)(nil), "api.ReturnRequest")
	proto.RegisterType((*ReturnResponse)(nil), "api.ReturnResponse")
	proto.RegisterType((*CancelRequest)(nil), "api.CancelRequest")
	proto.RegisterType((*CancelResponse)(nil), "api.CancelResponse")
	proto.RegisterType((*GetOrderRequest)(nil), "api.GetOrderRequest")
	proto.RegisterType((*GetOrderResponse)(nil), "api.GetOrderResponse")
	proto.RegisterType((*PaymentRequest)(nil), "api.PaymentRequest")
	proto.RegisterType((*PaymentResponse)(nil), "api.PaymentResponse")
	proto.RegisterType((*Event)(nil), "api.Event")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 890 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x5d, 0x6f, 0xf3, 0x34,
	0x14, 0x6e, 0xfa, 0xf1, 0xb6, 0x3d, 0xa5, 0x7d, 0x57, 0xb7, 0x5d, 0x43, 0x18, 0x50, 0xf9, 0x6a,
	0x62, 0x62, 0xa0, 0x82, 0xb4, 0x01, 0x42, 0xa8, 0xfb, 0xd0, 0x5a, 0x18, 0x5b, 0xc9, 0x10, 0x48,
	0xdc, 0x79, 0xa9, 0xe9, 0x22, 0x92, 0x36, 0x24, 0xee, 0x24, 0x7e, 0x00, 0x7f, 0x82, 0x7b, 0xfe,
	0x19, 0xd7, 0x5c, 0x72, 0x8d, 0xec, 0xd8, 0x69, 0xdc, 0x64, 0x5b, 0x07, 0x93, 0xde, 0xbb, 0xfa,
	0xb1, 0x7d, 0x9e, 0xf3, 0x9c, 0x13, 0x9f, 0x47, 0x85, 0x26, 0x09, 0xdc, 0x8f, 0x48, 0xe0, 0x1e,
	0x06, 0xe1, 0x92, 0x2d, 0x51, 0x89, 0x04, 0x2e, 0xf6, 0xa0, 0x3c, 0x61, 0xd4, 0x47, 0x7b, 0x50,
	0x1f, 0x85, 0xcc, 0x75, 0x3c, 0x3a, 0x39, 0x33, 0x8d, 0x81, 0xb1, 0xdf, 0xb4, 0xd7, 0x00, 0x42,
	0x50, 0xbe, 0x22, 0x3e, 0x35, 0x8b, 0x03, 0x63, 0xbf, 0x6e, 0x8b, 0xdf, 0xa8, 0x0b, 0x95, 0x69,
	0xe8, 0x3a, 0xd4, 0x2c, 0x89, 0xd3, 0xf1, 0x42, 0xc4, 0xb9, 0x27, 0xae, 0x47, 0x6e, 0x3d, 0x6a,
	0x96, 0x65, 0x1c, 0x05, 0xe0, 0x1e, 0x74, 0x38, 0x5b, 0x34, 0x59, 0xdc, 0xb0, 0xa5, 0xf3, 0x8b,
	0x4d, 0x7f, 0x5d, 0xd1, 0x88, 0xe1, 0x23, 0xe8, 0xea, 0x70, 0x14, 0x2c, 0x17, 0x11, 0x45, 0xef,
	0x43, 0x45, 0xe0, 0xa6, 0x31, 0x28, 0xed, 0x37, 0x86, 0xf5, 0x43, 0x9e, 0x3c, 0x47, 0xec, 0x18,
	0xc7, 0x07, 0xd0, 0x10, 0xcb, 0x38, 0xce, 0xe3, 0x22, 0xf0, 0x0f, 0xf0, 0x56, 0x7c, 0x58, 0x46,
	0x7f, 0x21, 0xc9, 0x78, 0x08, 0x48, 0xa4, 0x7d, 0xfd, 0xf3, 0xf6, 0xb9, 0x7c, 0x08, 0x1d, 0xed,
	0x8e, 0x4c, 0x69, 0x17, 0x5e, 0x8d, 0xfc, 0xe5, 0x6a, 0xc1, 0xe4, 0x0d, 0xb9, 0xc2, 0x5f, 0x03,
	0xb2, 0xe9, 0x6c, 0xe5, 0xd0, 0x74, 0xd9, 0x9e, 0x10, 0xb0, 0x8e, 0x55, 0xd4, 0x62, 0xf5, 0xa0,
	0xa3, 0xc5, 0x8a, 0xa9, 0xf1, 0x25, 0x74, 0x27, 0x0b, 0x27, 0xa4, 0x24, 0x7a, 0x09, 0x92, 0x3e,
	0xf4, 0x36, 0xa2, 0x49, 0x9a, 0x39, 0xf4, 0x6d, 0x3a, 0x77, 0x23, 0x46, 0xc3, 0xd3, 0x55, 0xc4,
	0x96, 0x3e, 0x0d, 0x15, 0xd3, 0x7b, 0x00, 0x0a, 0x4a, 0xa8, 0x52, 0x48, 0x6e, 0x47, 0x4c, 0xa8,
	0x8e, 0x66, 0xb3, 0x90, 0x46, 0x91, 0xe8, 0x49, 0xdd, 0x56, 0x4b, 0xfc, 0x39, 0x98, 0x59, 0x22,
	0x59, 0xe6, 0x27, 0x98, 0xf0, 0xa7, 0x80, 0x2e, 0x28, 0x7b, 0x66, 0x7e, 0xd8, 0x81, 0x8e, 0x76,
	0x6b, 0x3b, 0xb2, 0x67, 0xca, 0x3a, 0x82, 0xde, 0x19, 0xf5, 0x28, 0xa3, 0xcf, 0xcd, 0xee, 0x18,
	0x76, 0x37, 0x2f, 0x6e, 0x59, 0x8d, 0x09, 0xb4, 0x65, 0xc3, 0x7f, 0x74, 0xd9, 0x5d, 0xdc, 0xe0,
	0xff, 0xf8, 0x59, 0xf8, 0xd0, 0x9e, 0x7a, 0xc4, 0xa1, 0xd7, 0xe1, 0x6c, 0xfb, 0xbe, 0x1f, 0x43,
	0x83, 0xc4, 0x91, 0x2f, 0xdd, 0x88, 0x47, 0xe4, 0xb3, 0x60, 0x57, 0xcc, 0x82, 0x4c, 0x5e, 0x76,
	0xfa, 0x28, 0x1e, 0x03, 0x4a, 0xd3, 0x49, 0xbd, 0x26, 0x54, 0x05, 0x90, 0x90, 0xa9, 0x25, 0xdf,
	0xf9, 0x96, 0x46, 0x11, 0x99, 0xab, 0x6e, 0xa8, 0x25, 0xfe, 0xd3, 0x80, 0xa6, 0x4d, 0xd9, 0x2a,
	0x5c, 0x6c, 0x9b, 0x75, 0x8a, 0xa5, 0xa8, 0xb3, 0x0c, 0xa0, 0x61, 0xd3, 0x80, 0xe7, 0xe5, 0xd3,
	0x05, 0x13, 0x0d, 0xae, 0xd9, 0x69, 0x88, 0x2b, 0x1e, 0xa5, 0x14, 0x97, 0x1f, 0x57, 0x9c, 0x3a,
	0x8a, 0x3f, 0x80, 0x96, 0x4a, 0x73, 0xad, 0x56, 0x69, 0x32, 0x74, 0x4d, 0x13, 0x68, 0x9e, 0x92,
	0x85, 0x43, 0xbd, 0xff, 0x2d, 0x89, 0xd3, 0xaa, 0x50, 0x59, 0xda, 0x8d, 0x52, 0x1e, 0xc0, 0xeb,
	0x0b, 0xca, 0xb4, 0x2f, 0xe0, 0xc1, 0x8e, 0xe0, 0x3f, 0x0c, 0xd8, 0x59, 0x9f, 0xde, 0xf2, 0x45,
	0x6d, 0x94, 0xaf, 0xb8, 0x75, 0xf9, 0xf8, 0x5b, 0x9c, 0x12, 0x77, 0x26, 0x7b, 0x22, 0x7e, 0xf3,
	0xe4, 0x6e, 0xee, 0xdc, 0x20, 0xa0, 0x33, 0xe1, 0x67, 0x35, 0x5b, 0x2d, 0xb9, 0xea, 0x29, 0xf9,
	0x8d, 0x77, 0xec, 0x69, 0x21, 0x6d, 0x78, 0x9d, 0x9c, 0x95, 0xa3, 0xf0, 0x1a, 0x2a, 0xe7, 0xf7,
	0xbc, 0xdd, 0x2d, 0x28, 0xca, 0x0b, 0x75, 0xbb, 0x38, 0x39, 0xe3, 0x6f, 0xeb, 0x7b, 0xd7, 0xa7,
	0x11, 0x23, 0x7e, 0x20, 0xaa, 0x57, 0xb2, 0xd7, 0x40, 0xba, 0xb2, 0x25, 0xad, 0xb2, 0xc3, 0xdf,
	0x0d, 0xa8, 0x9e, 0x12, 0x46, 0xbc, 0xe5, 0x1c, 0x8d, 0x45, 0x95, 0xd3, 0xae, 0x8a, 0xcc, 0xc4,
	0x3e, 0x37, 0xfc, 0xd7, 0x7a, 0x3b, 0x67, 0x47, 0x26, 0x59, 0x40, 0x1f, 0x43, 0x55, 0x46, 0x42,
	0x3b, 0x6b, 0x03, 0x96, 0x37, 0xdb, 0x29, 0x44, 0xdd, 0x18, 0xfe, 0x55, 0x84, 0x4a, 0x4c, 0xf9,
	0x06, 0xb3, 0x40, 0xe7, 0xd0, 0xba, 0xa0, 0x2c, 0xe5, 0xb2, 0xa8, 0x2f, 0x8e, 0x65, 0xbd, 0xda,
	0x32, 0xb3, 0x1b, 0x49, 0x98, 0x31, 0xb4, 0x53, 0x76, 0xa9, 0x45, 0xca, 0x5a, 0xb2, 0x8c, 0x94,
	0xe7, 0xaf, 0x05, 0x74, 0x05, 0x1d, 0xcd, 0x13, 0x65, 0x2c, 0x29, 0x3b, 0xc7, 0x7b, 0x2d, 0x2b,
	0x6f, 0x2b, 0x29, 0xf3, 0xdf, 0x06, 0xd4, 0xd4, 0x57, 0x8f, 0xbe, 0x83, 0x9d, 0x4d, 0xbb, 0x43,
	0x7b, 0x32, 0x99, 0x5c, 0xbb, 0xb5, 0xde, 0x7d, 0x60, 0x37, 0xc9, 0xf7, 0x04, 0x1a, 0x29, 0x3f,
	0x93, 0x9a, 0xb3, 0xbe, 0x28, 0x35, 0xe7, 0x58, 0x1f, 0x2e, 0xa0, 0x6f, 0xa0, 0xa5, 0xbb, 0x0e,
	0x8a, 0x35, 0xe5, 0x7a, 0x98, 0xf5, 0x4e, 0xee, 0x5e, 0x22, 0xf8, 0x1f, 0x03, 0x2a, 0xe2, 0x3d,
	0xa1, 0xaf, 0x00, 0xd6, 0x83, 0x1d, 0xc5, 0x4f, 0x3b, 0x63, 0x2c, 0x56, 0x3f, 0x83, 0x27, 0x79,
	0x1d, 0x01, 0xc4, 0x73, 0x52, 0xb4, 0x00, 0xc9, 0x52, 0xa4, 0xe6, 0xbb, 0xd5, 0xd1, 0xb0, 0xe4,
	0xe2, 0x31, 0x34, 0xe2, 0x49, 0x17, 0x53, 0xc7, 0x37, 0xb5, 0x31, 0x2a, 0x6f, 0xea, 0xf3, 0x10,
	0x17, 0xd0, 0x67, 0x50, 0x53, 0x93, 0x0c, 0x75, 0x55, 0xc9, 0xb4, 0x7c, 0x7b, 0x1b, 0x68, 0x22,
	0x7c, 0x0c, 0x55, 0x39, 0x3c, 0xd0, 0x97, 0x7c, 0xc0, 0x3b, 0xd4, 0xbd, 0xa7, 0x0a, 0x89, 0xe9,
	0xf4, 0x41, 0x64, 0x75, 0x75, 0x30, 0x89, 0x04, 0x50, 0xe3, 0xd3, 0x8b, 0xa3, 0x27, 0xd5, 0x9f,
	0x2a, 0x87, 0x5f, 0x90, 0xc0, 0xbd, 0x7d, 0x25, 0xfe, 0x0f, 0x7c, 0xf2, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb3, 0x5d, 0x0b, 0xbc, 0x20, 0x0c, 0x00, 0x00,
}
